name: 'Terraform'

on:
  push:
    branches: [ main ]
    paths: [deployVM.tf, .github/workflows/terraform.yml] 
  workflow_run:
    

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
          creds: ${{ secrets.AZURE_CREDENTIALS }}
